[package]
name = "uart-rs"
version = "0.2.0"
authors = ["Patrick Oppel, patrick.oppel94@gmail.com"]
edition = "2018"

[dependencies]
serial = "0.4.0"
failure = "0.1.8"
toml = "0.4.0"
hal-stream = { version = "0.1.14", registry = "cube-os"}
display_derive = "0.0.0"
